<a href="https://colab.research.google.com/github/thanhnguyen2612/diveintocode-ml/blob/master/ML_preclass_ex3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics for Machine Learning Pre-Class assignment 3 Matrix Scratch
## [Problem 1] Matrix product is calculated manually

In [6]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


For each pair of row & column in matrix a and matrix b respectively, we compute their dot product. Resulting in a 3x3 matrix has:

1.   First row (row_0 of a * col_0 of b):
    *   [-1 2 3] x [0 0 2]     = 6
    *   [-1 2 3] x [2 2 9]     = 29
    *   [-1 2 3] x [1 -8 -1]   = -20
2.   Second row (row_1 of a * col_1 of b):
    *   [4 -5 6] x [0 0 2]     = 12
    *   [4 -5 6] x [2 2 9]     = 52
    *   [4 -5 6] x [1 -8 -1]   = 38
3.   Third row (row_2 of a * col_2 of b):
    *   [7 8 -9] x [0 0 2]     = -18
    *   [7 8 -9] x [2 2 9]     = -51
    *   [7 8 -9] x [1 -8 -1]   = -48

In [8]:
matrix_axb = np.array([[6, 29, -20], [12, 52, 38], [-18, -51, -48]])
matrix_axb

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## [Problem 2] Calculation by NumPy function

Computing in 3 ways

In [11]:
%%timeit
np.matmul(a_ndarray, b_ndarray)

The slowest run took 89.62 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.2 µs per loop


In [12]:
%%timeit
a_ndarray @ b_ndarray

The slowest run took 41.97 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.15 µs per loop


In [13]:
%%timeit
np.dot(a_ndarray, b_ndarray)

The slowest run took 27.11 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.24 µs per loop


## [Problem 3] Implementation of calculation of a certain element

Expect size of matrix A (a * m) and matrix B (m * b), therefore create a resulting matrix with size of (a * b)

In [18]:
mat_axb = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

for i in range(mat_axb.shape[0]):
    for j in range(mat_axb.shape[1]):
        sum = 0
        for k in range(a_ndarray.shape[1]):
            sum += a_ndarray[i][k] * b_ndarray[k][j]
        mat_axb[i][j] = sum

mat_axb

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## [Problem 4] Creating a function that performs matrix multiplication
## [Problem 5] Judge the input whose calculation is not defined
## [Problem 6] Transposition
Complete these problems at the same time

In [24]:
def matmul_custom(matrix_A, matrix_B):
    if matrix_A.shape[1] != matrix_B.shape[0]:
        return None

    mat_axb = np.zeros((matrix_A.shape[0], matrix_B.shape[1]))
    for i in range(mat_axb.shape[0]):
        for j in range(mat_axb.shape[1]):
            sum = 0
            for k in range(matrix_A.shape[1]):
                try:
                    sum += matrix_A[i][k] * matrix_B[k][j]
                except e:
                    print("Something wrong", e)
            mat_axb[i][j] = sum
    
    return mat_axb

mat_axb = matmul_custom(a_ndarray, b_ndarray)
mat_axb

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [25]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print("Cannot multiply them:", matmul_custom(d_ndarray, e_ndarray))

Cannot multiply them: None
