<a href="https://colab.research.google.com/github/thanhnguyen2612/diveintocode-ml/blob/master/ML_preclass_ex3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics for Machine Learning Pre-Class assignment 3 Matrix Scratch
## [Problem 1] Matrix product is calculated manually

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


For each pair of row & column in matrix a and matrix b respectively, we compute their dot product. Resulting in a 3x3 matrix has:

$$
AB = 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$

In [ ]:
matrix_axb = np.array([[6, 29, -20], [12, 52, 38], [-18, -51, -48]])
matrix_axb

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## [Problem 2] Calculation by NumPy function

Computing in 3 ways

In [ ]:
%%timeit
np.matmul(a_ndarray, b_ndarray)

The slowest run took 28.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.18 µs per loop


In [ ]:
%%timeit
a_ndarray @ b_ndarray

The slowest run took 37.45 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.14 µs per loop


In [ ]:
%%timeit
np.dot(a_ndarray, b_ndarray)

The slowest run took 34.71 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.22 µs per loop


## [Problem 3] Implementation of calculation of a certain element

Expect size of matrix A (a * m) and matrix B (m * b), therefore create a resulting matrix with size of (a * b)

In [ ]:
mat_axb = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

for i in range(mat_axb.shape[0]):
    for j in range(mat_axb.shape[1]):
        sum = 0
        for k in range(a_ndarray.shape[1]):
            sum += a_ndarray[i][k] * b_ndarray[k][j]
        mat_axb[i][j] = sum

mat_axb

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## [Problem 4] Creating a function that performs matrix multiplication
## [Problem 5] Judge the input whose calculation is not defined
Complete these problems at the same time

In [ ]:
def matmul_custom(matrix_A, matrix_B):
    if matrix_A.shape[1] != matrix_B.shape[0]:
        return None

    mat_axb = np.zeros((matrix_A.shape[0], matrix_B.shape[1]))
    for i in range(mat_axb.shape[0]):
        for j in range(mat_axb.shape[1]):
            sum = 0
            for k in range(matrix_A.shape[1]):
                try:
                    sum += matrix_A[i][k] * matrix_B[k][j]
                except e:
                    print("Something wrong", e)
            mat_axb[i][j] = sum
    
    return mat_axb

mat_axb = matmul_custom(a_ndarray, b_ndarray)
mat_axb

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [ ]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print("Cannot multiply them:", matmul_custom(d_ndarray, e_ndarray))

Cannot multiply them: None


## [Problem 6] Transposition
Transpose matrix E so that we have a valid computation of Matrix D (2x3) times Matrix E (3x2)

In [ ]:
print("D x E:", matmul_custom(d_ndarray, e_ndarray.T))

D x E: [[ 46.  -4.]
 [-34.  73.]]
