<a href="https://colab.research.google.com/github/thanhnguyen2612/diveintocode-ml/blob/master/ML_Week4_preclass_ass3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Machine Learning Pre-class assignment 3 Utilization of Object Orientation

## [Problem 1] Enumeration of classes used so far

*   Pandas library has classes: DataFrame, Series, etc.
*   matplotlib has: Figure, Axes, etc.
*   sklearn has: StandardScaler, KneighborsClassifier, LinearRegression, SVM, etc.




## [Problem 2] Enumeration of methods and instance variables used so far

Some methods used belonging to class:

*   DataFrame: head(), tail(), info(), describe(), drop(), select_dtypes(), isnull(), notnull(), etc.
*   matplotlib: set_title(), set_xlabel(), set_ylabel(), add_axes(), show(), etc.
*   sklearn: fit(), fit_transform(), transform, predict(), accuracy_score(), etc.



## [Problem 3] Creating a standardized class by scratch

Use sklearn library

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Variance :", scaler.var_)
X_std = scaler.transform(X)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]


Build from scratch

In [ ]:
import numpy as np

class ScratchStandardScaler():
    """
    Attributes
    ----------
    mean_ : ndarray, shape(n_features,)
    var_ : ndarray, shape(n_features,)
    """
    def fit(self, X):
        """
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)

    def transform(self, X):
        """
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        Returns
        ----------
        X_scaled : ndarray, shape (n_samples, n_features)
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [ ]:
data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean : {}".format(scratch_scaler.mean_))
print("Mean : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

print("\nCompare to sklearn library")
scaler = StandardScaler()
scaler.fit(X)
print("Mean : {}".format(scaler.mean_))
print("Mean : {}".format(scaler.var_))
X_std = scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Mean : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]

Compare to sklearn library
Mean : [4.86 3.31 1.45 0.22]
Mean : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.308879

## [Problem 4] Creating a class that performs 4 arithmetic operations

In [29]:
class ExampleClass():
    """
    Parameters
    ----------
    value : float or int
    Attributes
    ----------
    value : float or int
    """
    def __init__(self, value):
        assert type(value) in [int, float], "Initial value must be numeric"
        self.value = value
        print(f"Initial value {self.value} has been set")

    def add(self, value2):
        self.value += value2
    
    def subtract(self, value2):
        self.value -= value2
    
    def multiply(self, value2):
        self.value *= value2
    
    def divide(self, value2):
        self.value /= value2

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(3)
print("value : {}".format(example.value))
example.multiply(3)
print("value : {}".format(example.value))
example.divide(2)
print("value : {}".format(example.value))

Initial value 5 has been set
value : 5
value : 8
value : 5
value : 15
value : 7.5


In [30]:
print("Test invalid input")
error = ExampleClass('2')
print("value: {}".format(example.value))

Test invalid input


AssertionError: ignored